service: serverless-backend

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  environment:
    USERS_TABLE: nips_users
    FILES_TABLE: nips_files
    SECRET_KEY: ${env.SECRET_KEY}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  authenticate:
    handler: src/handlers/authentication.authenticateUser
    events:
      - http:
          path: authenticate
          method: post
  register:
    handler: src/handlers/authentication.registerUser
  uploadFile:
    handler: src/handlers/file.uploadHandler
  fetchFile:
    handler: src/handlers/file.fetchHandler
